import Head from "next/head";
import Link from "next/link";
import styles from "./layout.module.css";

export default function Layout({ children, title = "Crypto Price Tracker" }) {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <Link href="/" passHref>
          <a>
            <img src="/logo.gif" alt="logo" className={styles.header_logo} />
          </a>
        </Link>
      </header>
    </div>
  );
}
