import Head from "next/head";
import Image from "next/image";
import SearchBar from "../Components/Search-bar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cryto Price Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SearchBar type="text" />
      </main>

      <footer className={styles.footer}>Made with ♥ by Rishita</footer>
    </div>
  );
}
