import Head from "next/head";
import Image from "next/image";
import Logo from "../Components/Logo";
import SearchBar from "../Components/Search-bar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cryto Price Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SearchBar type="text" />
      </main>

      <footer>Made with ♥ by Rishita</footer>
    </div>
  );
}
